import { defineStore } from 'pinia'
import crossfilter from 'crossfilter2'

export const useTalentStore = defineStore('talent', {
  state: () => {
    const talents = [
      {
        id: 1,
        pic: '',
        cv: '',
        first: 'Damaris',
        last: 'Taib',
        email: 'd@gmail.com',
        phone: '123456789',
        title: 'Software Engineer',
        employment: 'fulltime',
        contract: '',
        remark: '',
        department: 'IT',
        hire: '',
        wage: 5000,
        summary: '',
        skill: ['Vue', 'SEO', 'Python'],
        edu: [],
        gender: 'female',
        dob: '1973-02-18',
        marital: false,
      },
      {
        id: 2,
        pic: '',
        cv: '',
        first: 'John',
        last: 'Smith',
        email: 'john.s@gmail.com',
        phone: '987654321',
        title: 'Frontend Developer',
        employment: 'fulltime',
        contract: '',
        remark: '',
        department: 'IT',
        hire: '',
        wage: 4800,
        summary: '',
        skill: ['Javascript', 'CRM'],
        edu: [],
        gender: 'male',
        dob: '1990-05-15',
        marital: true,
      },
      {
        id: 3,
        pic: '',
        cv: '',
        first: 'Sarah',
        last: 'Johnson',
        email: 'sarah.j@gmail.com',
        phone: '456789123',
        title: 'UX Designer',
        employment: 'parttime',
        contract: '',
        remark: '',
        department: 'Design',
        hire: '',
        wage: 4200,
        summary: '',
        skill: ['Javascript', 'Vue'],
        edu: [],
        gender: 'female',
        dob: '1988-11-30',
        marital: true,
      },
      {
        id: 4,
        pic: '',
        cv: '',
        first: 'Michael',
        last: 'Chen',
        email: 'm.chen@gmail.com',
        phone: '789123456',
        title: 'Backend Developer',
        employment: 'fulltime',
        contract: '',
        remark: '',
        department: 'IT',
        hire: '',
        wage: 5200,
        summary: '',
        skill: ['Node', 'Python'],
        edu: [],
        gender: 'male',
        dob: '1985-07-22',
        marital: false,
      },
      {
        id: 5,
        pic: '',
        cv: '',
        first: 'Emma',
        last: 'Wilson',
        email: 'e.wilson@gmail.com',
        phone: '321654987',
        title: 'Project Manager',
        employment: 'fulltime',
        contract: '',
        remark: '',
        department: 'Management',
        hire: '',
        wage: 6000,
        summary: '',
        skill: ['CRM', 'SEO', 'Excel'],
        edu: [],
        gender: 'female',
        dob: '1982-09-10',
        marital: true,
      },
      {
        id: 6,
        pic: '',
        cv: '',
        first: 'David',
        last: 'Lee',
        email: 'd.lee@gmail.com',
        phone: '147258369',
        title: 'Data Scientist',
        employment: 'fulltime',
        contract: '',
        remark: '',
        department: 'Data',
        hire: '',
        wage: 5500,
        summary: '',
        skill: ['Python', 'Excel'],
        edu: [],
        gender: 'male',
        dob: '1992-03-25',
        marital: false,
      },
      {
        id: 7,
        pic: '',
        cv: '',
        first: 'Lisa',
        last: 'Garcia',
        email: 'l.garcia@gmail.com',
        phone: '258369147',
        title: 'Marketing Specialist',
        employment: 'parttime',
        contract: '',
        remark: '',
        department: 'Marketing',
        hire: '',
        wage: 3800,
        summary: '',
        skill: ['Word', 'Excel', 'CRM'],
        edu: [],
        gender: 'female',
        dob: '1991-12-05',
        marital: false,
      },
      {
        id: 8,
        pic: '',
        cv: '',
        first: 'Robert',
        last: 'Taylor',
        email: 'r.taylor@gmail.com',
        phone: '369147258',
        title: 'DevOps Engineer',
        employment: 'fulltime',
        contract: '',
        remark: '',
        department: 'IT',
        hire: '',
        wage: 5800,
        summary: '',
        skill: ['Node', 'Python', 'Vue'],
        edu: [],
        gender: 'male',
        dob: '1987-08-15',
        marital: true,
      },
      {
        id: 9,
        pic: '',
        cv: '',
        first: 'Amanda',
        last: 'Brown',
        email: 'a.brown@gmail.com',
        phone: '741852963',
        title: 'HR Manager',
        employment: 'fulltime',
        contract: '',
        remark: '',
        department: 'HR',
        hire: '',
        wage: 5300,
        summary: '',
        skill: ['CRM', 'Word', 'Excel'],
        edu: [],
        gender: 'female',
        dob: '1984-06-20',
        marital: true,
      },
      {
        id: 10,
        pic: '',
        cv: '',
        first: 'Kevin',
        last: 'Martinez',
        email: 'k.martinez@gmail.com',
        phone: '963852741',
        title: 'Quality Assurance',
        employment: 'fulltime',
        contract: '',
        remark: '',
        department: 'IT',
        hire: '',
        wage: 4600,
        summary: '',
        skill: ['Python', 'Node'],
        edu: [],
        gender: 'male',
        dob: '1989-04-12',
        marital: false,
      },
    ]

    const cf = crossfilter(talents)

    return {
      talents,
      people: cf,
    }
  },
})
